spring.application.name=MongoApplication
spring.mongodb.uri=mongodb+srv://ord_admin:BI7YjmYpl7NocOKk@cluster0.ahmvvc5.mongodb.net/?appName=Cluster0
spring.mongodb.database=Cluster0

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=equipeord345@gmail.com
spring.mail.password=vpam oqsl tzkn vvmw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true