spring.application.name=MongoApplication
<<<<<<< HEAD
spring.mongodb.uri=mongodb+srv://Ord_db:Fatec777@clusterord.ueywqi5.mongodb.net/?appName=ClusterORD
spring.mongodb.database=ClusterORD

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=edsonpg.alves@gmail.com
spring.mail.password=wwsk jlnk xlij jrst

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
=======
spring.mongodb.uri=mongodb+srv://equipeord345:Fatec777@clusterord.kymqome.mongodb.net/?appName=ClusterORD
spring.mongodb.database=ClusterORD
>>>>>>> dc7941fd091cc74bc463c2b0098e0188119e28db
